n  = 2  # An integer 'n' that is the length of the ngrams.
s  = 1  # An integer 's' that is the length of the slide.
filename = file.txt # Name of the file<should be in the same folder>

ngrams:
	python ngrams.py $(n) $(s) prog1 out_file.txt >1.txt
	python ngrams.py $(n) $(s) prog2 oru >2.txt
	python ngrams.py $(n) $(s) prog3 oru >3.txt
	python ngrams.py $(n) $(s) prog4 oru >4.txt
	python ngrams.py $(n) $(s) prog5 oru >5.txt
	python ngrams.py $(n) $(s) prog6 oru >6.txt
